[platformio]
default_envs = esp32e_full

[env:esp32e_full]
platform = platformio/espressif32@6.7.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = ../../../Esp32Base/partitions/esp32-4mb-ota-balanced.csv
board_build.filesystem = littlefs
lib_deps =
  ArduinoOTA
  WiFi
  DNSServer
  ESPmDNS
  LittleFS
  WebServer
  Update
  symlink://../../../Esp32Base
  symlink://../../lib/Esp32At24cRecordStore
  symlink://../../lib/Esp32EncodedDcMotor
  symlink://../../lib/Esp32MotorCurrentGuard
build_flags =
  -D ESP32BASE_PROFILE=ESP32BASE_PROFILE_FULL
  -D ESP32BASE_ENABLE_APP_CONFIG=1
  -D ESP32BASE_APP_CONFIG_MAX_GROUPS=8
  -D ESP32BASE_APP_CONFIG_MAX_FIELDS=96
  -D ESP32BASE_DEFAULT_HOSTNAME=\"esp32-farmdoor\"
  -D ESP32BASE_LOG_LEVEL=ESP32BASE_LOG_INFO
  -D ESP32BASE_EB_FILELOG_DEFAULT_MODE=ESP32BASE_FILELOG_MODE_INFO
  -D FARMAUTO_FARMDOOR_ENABLE_INA240A2=1
  -I ${platformio.packages_dir}/framework-arduinoespressif32/libraries/ArduinoOTA/src
  -I ${platformio.packages_dir}/framework-arduinoespressif32/libraries/FS/src
  -I ${platformio.packages_dir}/framework-arduinoespressif32/libraries/Hash/src
  -I ${platformio.packages_dir}/framework-arduinoespressif32/libraries/DNSServer/src
  -I ${platformio.packages_dir}/framework-arduinoespressif32/libraries/ESPmDNS/src
  -I ${platformio.packages_dir}/framework-arduinoespressif32/libraries/LittleFS/src
  -I ${platformio.packages_dir}/framework-arduinoespressif32/libraries/WebServer/src
  -I ${platformio.packages_dir}/framework-arduinoespressif32/libraries/WiFi/src
  -I ${platformio.packages_dir}/framework-arduinoespressif32/libraries/Update/src
