[platformio]
default_envs = STC8H8K64U

[env:STC8H8K64U]
platform = intel_mcs51
board = STC8H8K64U
board_upload.maximum_size = 65535
build_flags =
    --stack-auto
    -I../../../../codex_dir/Stc8hBase/core
    -I../../../../codex_dir/Stc8hBase/hal
    -I../../../../codex_dir/Stc8hBase/drivers
    -I../../../../codex_dir/Stc8hBase/board/stc8h8k64u_lqfp48_base
    -I../../shared/protocol
    -Isrc/action
    -Isrc/board
    -Isrc/protocol
    -DSTC8H_CONFIG_INCLUDE=\"board_config.h\"
    -DSTC8H_PINS_INCLUDE=\"board_pins.h\"
    -DSTC8H_UART_ENABLE_UART1=1
